spring:
  main:
    banner-mode: "off"
  application:
    name: pauta-voting
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sicredi_pauta_voting
      username: root
      password: root
      authentication-database: admin

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.apache.http: INFO
    org.springframework.web: INFO

client:
  url:
    user-info: https://user-info.herokuapp.com

feign:
  logger:
    level: FULL

voting:
  session:
    time: 1